export const mockAds = [
  {
    adId: 213232,
    user: {
      login: 'aboba',
    },
    title: 'Game 1',
    background_image: '/game.jpg',
    status: 'CREATED',
  },
  {
    adId: 2123123232,
    user: {
      login: 'cherishkin',
    },
    title: 'Game 2',
    background_image: '/game.jpg',
    status: 'CREATED',
  },
  {
    adId: 22321,
    user: {
      login: 'aboba',
    },
    title: 'Apanovich',
    background_image: '/game.jpg',
    status: 'BLOCKED',
  },
  {
    adId: 22321122399,
    user: {
      login: 'aboba',
    },
    title: 'Apanovich 2323',
    background_image: '/game.jpg',
    status: 'APPROVED',
  },
  // {
  //   id: 2456789123,
  //   slug: 'Ivan',
  //   title: 'The Enigmatic Journey',
  //   playtime: 104,
  //   metacritic: 75,
  //   background_image: '/game.jpg',
  //   isApproved: 'true',
  // },
  // {
  //   id: 8756432198,
  //   slug: 'Olga',
  //   title: 'Mystical Adventure',
  //   playtime: 42,
  //   metacritic: 92,
  //   background_image: '/game.jpg',
  //   isApproved: 'false',
  // },
  // {
  //   id: 3612345876,
  //   slug: 'Pavel',
  //   title: 'Epic Quest',
  //   playtime: 89,
  //   metacritic: 80,
  //   background_image: '/game.jpg',
  //   isApproved: 'true',
  // },
  // {
  //   id: 9845623765,
  //   slug: 'Elena',
  //   title: 'Legendary Odyssey',
  //   playtime: 57,
  //   metacritic: 88,
  //   background_image: '/game.jpg',
  //   isApproved: 'new',
  // },
  // {
  //   id: 7890123456,
  //   slug: 'Alexey',
  //   title: 'Chronicles of Destiny',
  //   playtime: 120,
  //   metacritic: 95,
  //   background_image: '/game.jpg',
  //   isApproved: 'new',
  // },
  // {
  //   id: 6543217890,
  //   slug: 'Yulia',
  //   title: 'Enchanted Realms',
  //   playtime: 33,
  //   metacritic: 78,
  //   background_image: '/game.jpg',
  //   isApproved: 'false',
  // },
  // {
  //   id: 876542323,
  //   slug: 'Dmitry',
  //   title: 'Realm of Legends',
  //   playtime: 76,
  //   metacritic: 87,
  //   background_image: '/game.jpg',
  //   isApproved: 'true',
  // },
  // {
  //   id: 2345678901,
  //   slug: 'Maria',
  //   title: 'Eternal Fantasy',
  //   playtime: 95,
  //   metacritic: 91,
  //   background_image: '/game.jpg',
  //   isApproved: 'false',
  // },
  // {
  //   id: 5432109876,
  //   slug: 'Natalia',
  //   title: 'Shadowed Secrets',
  //   playtime: 50,
  //   metacritic: 82,
  //   background_image: '/game.jpg',
  //   isApproved: 'true',
  // },
  // {
  //   id: 1098765432,
  //   slug: 'Andrei',
  //   title: 'Quest for Glory',
  //   playtime: 63,
  //   metacritic: 79,
  //   background_image: '/game.jpg',
  //   isApproved: 'new',
  // },
  // {
  //   id: 7654321098,
  //   slug: 'Katerina',
  //   title: 'Whispers in the Wind',
  //   playtime: 88,
  //   metacritic: 94,
  //   background_image: '/game.jpg',
  //   isApproved: 'false',
  // },
  // {
  //   id: 8765432109,
  //   slug: 'Vladimir',
  //   title: 'Legends of Valor',
  //   playtime: 72,
  //   metacritic: 85,
  //   background_image: '/game.jpg',
  //   isApproved: 'true',
  // },
  // {
  //   id: 1234567890,
  //   slug: 'Svetlana',
  //   title: 'Sorcerer’s Tale',
  //   playtime: 105,
  //   metacritic: 89,
  //   background_image: '/game.jpg',
  //   isApproved: 'false',
  // },
  // {
  //   id: 9876543210,
  //   slug: 'Yuri',
  //   title: 'Mythical Chronicles',
  //   playtime: 40,
  //   metacritic: 77,
  //   background_image: '/game.jpg',
  //   isApproved: 'new',
  // },
  // {
  //   id: 5678901234,
  //   slug: 'Anastasia',
  //   title: 'Epic Legends',
  //   playtime: 68,
  //   metacritic: 83,
  //   background_image: '/game.jpg',
  //   isApproved: 'true',
  // },
];
