import Header from '@/components/Header';
import { LayoutProps } from '@/helper/Types/game';
import { currentUserData } from '@/store/currentUser/currentUserSelector';
import { logoutAction } from '@/store/logout/logoutThunk';
import { AppDispatch } from '@/store/store';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';

export default function RegistrationLayout({ children, title }: LayoutProps) {
  const dispatch = useDispatch<AppDispatch>();
  const currentUser = useSelector(currentUserData);
  useEffect(() => {
    if (currentUser.status === 'BLOCKED') {
      dispatch(logoutAction());
    }
  }, [dispatch, currentUser.status]);
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <Header />
        {children}
      </div>
    </>
  );
}
